---
# @author Stephen Damian <contact@damian-freelance.fr>
# @link   https://github.com/s-damian/ansible-web-server-debian

- name: Update and upgrade
  apt:
    update_cache: yes
    upgrade: 'yes'

- name: Installation
  apt:
    pkg:
      - unzip
      - wget
    state: latest
