---
# @author Stephen Damian <contact@devandweb.fr>
# @link   https://github.com/s-damian/ansible-lemp-server-debian

- name: Update and upgrade
  apt:
    update_cache: yes
    upgrade: 'yes'

- name: Installation
  apt:
    pkg:
      - unzip
    state: latest
