---
# @author Stephen Damian <contact@damian-freelance.fr>
# @link   https://github.com/s-damian/ansible-web-server-debian

- name: Remove apache2
  apt:
    name: apache2
    state: absent
    purge: yes
    force: yes
  when: http_server != "apache"

- name: Change the timezone - Put {{ linux_timezone }}
  shell: sudo timedatectl set-timezone {{ linux_timezone }}

- name: Update and upgrade
  apt:
    update_cache: yes
    upgrade: 'yes'
