---
# @author Stephen Damian <contact@damian-freelance.fr>
# @link   https://github.com/s-damian/ansible-web-server-debian

# ------------------------------ Install Nginx ------------------------------
- name: Installation of useful packages
  apt:
    pkg:
      - curl
      - gnupg2
      - ca-certificates
      - lsb-release
      - debian-archive-keyring
    state: latest
  when: http_server == "nginx"

- name: curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor | sudo tee /usr/share/keyrings/nginx-archive-keyring.gpg >/dev/null
  shell: curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor | sudo tee /usr/share/keyrings/nginx-archive-keyring.gpg >/dev/null
  when: http_server == "nginx"

- name: Configure apt repository for stable nginx packages
  shell: sh -c 'echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/debian $(lsb_release -sc) nginx" > /etc/apt/sources.list.d/nginx.list'
  when: http_server == "nginx"

- name: Update
  apt:
    update_cache: yes
  when: http_server == "nginx"

- name: Install nginx
  apt:
    name: nginx
    state: latest
  when: http_server == "nginx"
# ------------------------------ /Install Nginx ------------------------------

- name: Start nginx
  service:
    name: nginx
    state: started
  when: http_server == "nginx"
