---
# @author Stephen Damian <contact@damian-freelance.fr>
# @link   https://github.com/s-damian/ansible-web-server-debian

- name: Installing the LEMP server
  hosts: webservers
  remote_user: root

  # Variables
  vars:
    # ---------- OS ---------- #
    # REQUIRED
    # Your linux user
    linux_user: root

    # Path of your websites in your user directory
    # /home/{{ linux_user }}/www/{{ website_path }}/{{ domain }}
    website_path: sites

    # Set OS and PHP timezone
    linux_timezone: UTC
    # ---------- /OS ---------- #

    # ---------- Your websites ---------- #
    # REQUIRED
    # Your domains
    # You must put your domains without the "www." (example: your-domain.com).
    # But you can use a subdomain (example: subdomain.your-domain.com).
    domains:
      - your-domain.com
    
    # Path of the public directory of your website
    # /home/{{ linux_user }}/www/{{ website_path }}/{{ domain }}/{{ public_path }}
    public_path: public
    # ---------- /Your websites ---------- #

    # ---------- HTTP server ---------- #
    # Supported: "nginx" or "apache"
    http_server: nginx
    # ---------- /HTTP server ---------- #

    # ---------- Versions ---------- #
    # PHP version. Supported: 8.0, 8.1, 8.2
    version_php: "8.2"

    # ---------- MySQL ---------- #
    # MySQL root password
    mysql_user_home: /root
    mysql_user_name: root
    mysql_user_password: root

    # MySQL database configuration
    mysql_port: "3306"
    mysql_bind_address: '0.0.0.0'
    mysql_datadir: /var/lib/mysql

    # MySQL databases
    mysql_databases:
      - name: laravel
        collation: utf8_general_ci
        encoding: utf8
        replicate: 1
    # ---------- /MySQL ---------- #

  # Roles
  roles:
    - start
    - domains-architecture
    - php
    - nginx-step1 # Install Nginx
    - nginx-step2 # Conf Nginx
    - role: geerlingguy.mysql
      become: yes
    - end
...
